spring:
  redis:
    host: localhost
    port: 6379
jpa:
  show-sql: true
  hibernate:
    ddl-auto: create


logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
